# Generated by Django 4.2 on 2023-04-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propriedade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutorRural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propriedade.propriedade')),
            ],
        ),
    ]
