# Generated by Django 4.2 on 2023-04-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsaveistecnicos',
            options={'verbose_name_plural': 'Responsável técnico'},
        ),
        migrations.AddField(
            model_name='diagnosticorecomendacaotecnica',
            name='dosagem',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
