# Generated by Django 4.2 on 2023-04-29 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_responsaveistecnicos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='quantidade_a_adquirir',
            field=models.CharField(max_length=255),
        ),
    ]
