# Generated by Django 4.2 on 2023-04-29 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_diagnosticorecomendacaotecnica_quantidade_a_adquirir'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosticos_recomendacoes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.diagnosticorecomendacaotecnica')),
                ('produtor_rural', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.produtorrural')),
                ('responsavel_tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.responsaveistecnicos')),
            ],
        ),
    ]
