# Generated by Django 4.2 on 2023-05-01 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_receita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receituario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Receituário',
            },
        ),
        migrations.AlterField(
            model_name='classetoxicologica',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='classetoxicologica',
            name='nivel_categoria',
            field=models.IntegerField(unique=True, verbose_name='Nível da categoria'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='alvo',
            field=models.CharField(max_length=255, verbose_name='Alvo'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='area_a_tratar',
            field=models.CharField(max_length=255, verbose_name='Área a tratar'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='classe_toxicologica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.classetoxicologica', verbose_name='Classe toxicológica'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='cultura',
            field=models.CharField(max_length=255, verbose_name='Cultura'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='dosagem',
            field=models.CharField(max_length=255, verbose_name='Dosagem'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='epoca_aplicacao',
            field=models.TextField(verbose_name='Época de aplicação'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='equipamento_aplicacao',
            field=models.CharField(max_length=255, verbose_name='Equipamento de aplicação'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='intervalo_de_seguranca',
            field=models.CharField(max_length=255, verbose_name='Intervalo de segurança'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='modalidade_aplicacao',
            field=models.CharField(max_length=255, verbose_name='Modalidade de aplicação'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='numero_aplicacoes',
            field=models.IntegerField(verbose_name='Número de aplicações'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='produto_comercial',
            field=models.CharField(max_length=255, verbose_name='Produto comercial'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='quantidade_a_adquirir',
            field=models.CharField(max_length=255, verbose_name='Quantidade a adquirir'),
        ),
        migrations.AlterField(
            model_name='diagnosticorecomendacaotecnica',
            name='volume_da_calda',
            field=models.CharField(max_length=255, verbose_name='Volume da calda'),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produtorrural',
            name='propriedade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.propriedade', verbose_name='Propriedade'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='cnpj',
            field=models.CharField(help_text='Digite no formato xx.xxx.xxx/xxxx-XX para CNPJ.', max_length=18, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='descricao',
            field=models.CharField(max_length=255, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='latitude',
            field=models.CharField(max_length=10, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='local',
            field=models.TextField(verbose_name='Local'),
        ),
        migrations.AlterField(
            model_name='propriedade',
            name='longitude',
            field=models.CharField(max_length=10, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='responsaveistecnicos',
            name='cnpj',
            field=models.CharField(help_text='Digite no formato xx.xxx.xxx/xxxx-XX para CNPJ ou xxx.xxx.xxx-xx para CPF.', max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='responsaveistecnicos',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='responsaveistecnicos',
            name='numero_registro',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número de registro'),
        ),
        migrations.DeleteModel(
            name='Receita',
        ),
        migrations.AddField(
            model_name='receituario',
            name='diagnosticos_recomendacoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.diagnosticorecomendacaotecnica', verbose_name='Diagnóstico e recomendaçõe técnica'),
        ),
        migrations.AddField(
            model_name='receituario',
            name='produtor_rural',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.produtorrural', verbose_name='Produtor rural'),
        ),
        migrations.AddField(
            model_name='receituario',
            name='responsavel_tecnico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='principal.responsaveistecnicos', verbose_name='Responsável técnico'),
        ),
    ]
