# Generated by Django 4.2 on 2023-04-29 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classeToxicologica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoRecomendacaoTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=255)),
                ('produto_comercial', models.CharField(max_length=255)),
                ('area_a_tratar', models.CharField(max_length=255)),
                ('volume_da_calda', models.CharField(max_length=255)),
                ('modalidade_aplicacao', models.CharField(max_length=255)),
                ('alvo', models.CharField(max_length=255)),
                ('intervalo_de_seguranca', models.CharField(max_length=255)),
                ('equipamento_aplicacao', models.CharField(max_length=255)),
                ('quantidade_a_adquirir', models.IntegerField()),
                ('numero_aplicacoes', models.IntegerField()),
                ('epoca_aplicacao', models.TextField()),
                ('classe_toxicologica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='classeToxicologica.classetoxicologica')),
            ],
        ),
    ]
